### ISSUE TITLE
[BUG] constrained routes crash after updating to v6

### ISSUE THREAD

**Issue by jose-sherpa** [DataDog/libdatadog#361]
**Describe the bug**
After updating `ddtrace` to `1.21.0` which updated `libdatadog` to `6.0.0.2.0` and then visiting a route that has a constraint on it and when the session does not match that constraint, a `NoMethodError` gets thrown.

**To Reproduce**
1. Have datadog tracing enabled
2. Create a route with a constraint that won't match
3. Start your rails server
4. Visit the route
5. See error

Simple example:

`routes.rb`
```
  constraints -> { false } do
    get "/test_path", to: redirect("/404.html")
  end
```
Then visit that path with datadog tracing enabled

**Expected behavior**
An `ActionController::RoutingError` should be thrown causing a 404 status instead of the `NoMethodError` which causes a 500 status to be returned.

**Errors or warnings received**
```
     NoMethodError:
       undefined method `[]' for #<ActionDispatch::Journey::Route
```
Thrown from:
```
.rvm/gems/ruby-3.2.2/gems/ddtrace-1.21.0/lib/datadog/tracing/contrib/rails/patcher.rb:18:in `find_routes'
```
In this code:
```
integration_route = result.first[2].path.spec.to_s.gsub(/\(\.:format\)/, '') if result.any?
```

**Comment by ivoanjo** [comment]
Hey @jose-sherpa sorry you ran into this! This is being tracked in https://github.com/DataDog/dd-trace-rb/issues/3526 ; TL;DR we're planning on releasing a hotfix 1.21.1 very soon to address the issue.

If you don't mind, I'll close this issue, and we'll continue to provide updates in the one listed above.

**Comment by ivoanjo** [comment]
@jose-sherpa version 1.21.1 of the Ruby library has now been released with the fix! Thanks for the patience! :)

**Comment by jose-sherpa** [comment]
> @jose-sherpa version 1.21.1 of the Ruby library has now been released with the fix! Thanks for the patience! :)

Thank you for the super fast turnaround!
